# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'row_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 159)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(11, 11, 181, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.row = QtWidgets.QLineEdit(Form)
        self.row.setGeometry(QtCore.QRect(10, 60, 541, 31))
        self.row.setObjectName("row")
        self.Done = QtWidgets.QPushButton(Form)
        self.Done.setGeometry(QtCore.QRect(10, 100, 93, 28))
        self.Done.setObjectName("Done")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Введи данные"))
        self.Done.setText(_translate("Form", "Готово"))
